=== hiroyasub/cayenne-cregit/framework/cayenne-jdk1.5-unpublished/src/main/resources/org/apache/cayenne/modelMap.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
  Licensed to the Apache Software Foundation (ASF) under one
  or more contributor license agreements.  See the NOTICE file
  distributed with this work for additional information
  regarding copyright ownership.  The ASF licenses this file
  to you under the Apache License, Version 2.0 (the
  "License"); you may not use this file except in compliance
  with the License.  You may obtain a copy of the License at
  
  http://www.apache.org/licenses/LICENSE-2.0
  
  Unless required by applicable law or agreed to in writing,
  software distributed under the License is distributed on an
  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  KIND, either express or implied.  See the License for the
  specific language governing permissions and limitations
  under the License.
-->

<!-- Cayenne entity map schema --> 
<xs:schema targetNamespace="http://cayenne.apache.org/xml/ns/modelMap" xmlns:cay="http://cayenne.apache.org/xml/ns/modelMap" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" version="1.0">
  <xs:element name="data-map">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:property"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:db-entity"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:obj-entity"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:db-relationship"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:obj-relationship"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:query"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:entity-listener"/>
      </xs:sequence>
      <xs:attribute name="project-version" use="required" type="xs:decimal"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="db-entity">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="cay:db-attribute"/>
      </xs:sequence>
      <xs:attribute name="name" use="required" type="xs:string"/>
      <xs:attribute name="schema" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="db-attribute">
    <xs:complexType>
      <xs:attribute name="isMandatory" type="xs:boolean">
        <xs:annotation> 
          <xs:documentation>If true, the value of this attribute cannot be null.</xs:documentation> 
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="isPrimaryKey" type="xs:boolean">
        <xs:annotation>
          <xs:documentation>If true, the value of attribute is unique and used as a primary key identifier.</xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="length" type="xs:integer"/>
      <xs:attribute name="name" use="required" type="xs:string"/>
      <xs:attribute name="scale" type="xs:integer"/>
      <xs:attribute name="type" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="obj-entity">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" ref="cay:qualifier"/>
        <xs:element maxOccurs="unbounded" ref="cay:obj-attribute"/>
        <xs:sequence minOccurs="0">
          <xs:element ref="cay:entity-listener"/>
          <xs:element ref="cay:pre-persist"/>
          <xs:element ref="cay:post-update"/>
        </xs:sequence>
      </xs:sequence>
      <xs:attribute name="className" use="required" type="xs:string"/>
      <xs:attribute name="clientClassName" use="required" type="xs:string"/>
      <xs:attribute name="clientSuperClassName" use="required" type="xs:string"/>
      <xs:attribute name="dbEntityName" use="required" type="xs:string"/>
      <xs:attribute name="lock-type" type="xs:string"/>
      <xs:attribute name="name" use="required" type="xs:string"/>
      <xs:attribute name="superClassName" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="qualifier" type="xs:string"/>
  <xs:element name="obj-attribute">
    <xs:complexType>
      <xs:attribute name="db-attribute-path" use="required" type="xs:string"/>
      <xs:attribute name="lock" type="xs:boolean"/>
      <xs:attribute name="name" use="required" type="xs:string"/>
      <xs:attribute name="type" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="db-relationship">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="cay:db-attribute-pair"/>
      </xs:sequence>
      <xs:attribute name="name" use="required" type="xs:string"/>
      <xs:attribute name="source" use="required" type="xs:string"/>
      <xs:attribute name="target" use="required" type="xs:string"/>
      <xs:attribute name="toDependentPK" type="xs:boolean"/>
      <xs:attribute name="toMany" use="required" type="xs:boolean"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="db-attribute-pair">
    <xs:complexType>
      <xs:attribute name="source" use="required" type="xs:string"/>
      <xs:attribute name="target" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="obj-relationship">
    <xs:complexType>
      <xs:attribute name="db-relationship-path" use="required" type="xs:string"/>
      <xs:attribute name="deleteRule" type="xs:string"/>
      <xs:attribute name="lock" type="xs:boolean"/>
      <xs:attribute name="name" use="required" type="xs:string"/>
      <xs:attribute name="source" use="required" type="xs:string"/>
      <xs:attribute name="target" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="query">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:property"/>
        <xs:element ref="cay:sql"/>
      </xs:sequence>
      <xs:attribute name="factory" use="required"/>
      <xs:attribute name="name" use="required" type="xs:string"/>
      <xs:attribute name="root" use="required" type="xs:string"/>
      <xs:attribute name="root-name" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="sql" type="xs:string"/>
  <xs:element name="property">
    <xs:complexType>
      <xs:attribute name="name" use="required" type="xs:string"/>
      <xs:attribute name="value" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="entity-listener">
    <xs:complexType>
      <xs:sequence>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:pre-persist"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:post-persist"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:pre-update"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:post-update"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:pre-remove"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:post-remove"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:post-load"/>
      </xs:sequence>
      <xs:attribute name="class" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="pre-update">
    <xs:complexType>
      <xs:attribute name="method-name" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="post-persist">
    <xs:complexType>
      <xs:attribute name="method-name" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="post-update">
    <xs:complexType>
      <xs:attribute name="method-name" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="pre-persist">
    <xs:complexType>
      <xs:attribute name="method-name" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="post-remove">
    <xs:complexType>
      <xs:attribute name="method-name" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="post-load">
    <xs:complexType>
      <xs:attribute name="method-name" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="pre-remove">
    <xs:complexType>
      <xs:attribute name="method-name" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== hiroyasub/cayenne-cregit/cayenne-server/src/test/resources/relationships1.map.xml
<?xml version="1.0" encoding="utf-8"?>
<data-map xmlns="http://cayenne.apache.org/schema/7/modelMap"
	 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	 xsi:schemaLocation="http://cayenne.apache.org/schema/7/modelMap http://cayenne.apache.org/schema/7/modelMap.xsd"
	 project-version="7">
	<property name="defaultPackage" value="org.apache.cayenne.testdo.r1"/>
	<db-entity name="ACTIVITY">
		<db-attribute name="ACTIVITY_ID" type="VARCHAR" isPrimaryKey="true" isMandatory="true" length="50"/>
		<db-attribute name="APPOINT_DATE" type="DATE" isMandatory="true"/>
		<db-attribute name="APPOINT_NO" type="INTEGER" isMandatory="true"/>
	</db-entity>
	<db-entity name="RESULT">
		<db-attribute name="APPOINT_DATE" type="DATE" isPrimaryKey="true" isMandatory="true"/>
		<db-attribute name="APPOINT_NO" type="INTEGER" isPrimaryKey="true" isMandatory="true"/>
		<db-attribute name="RESULTNAME" type="VARCHAR" isPrimaryKey="true" isMandatory="true" length="50"/>
	</db-entity>
	<obj-entity name="Activity" className="org.apache.cayenne.testdo.r1.Activity" dbEntityName="ACTIVITY">
		<obj-attribute name="appointmentDate" type="java.sql.Date" db-attribute-path="APPOINT_DATE"/>
		<obj-attribute name="appointmentNo" type="int" db-attribute-path="APPOINT_NO"/>
	</obj-entity>
	<obj-entity name="ActivityResult" className="org.apache.cayenne.testdo.r1.ActivityResult" dbEntityName="RESULT">
		<obj-attribute name="appointDate" type="java.sql.Date" db-attribute-path="APPOINT_DATE"/>
		<obj-attribute name="appointNo" type="int" db-attribute-path="APPOINT_NO"/>
		<obj-attribute name="field" type="java.lang.String" db-attribute-path="RESULTNAME"/>
	</obj-entity>
	<db-relationship name="ActivityResultsRel" source="ACTIVITY" target="RESULT" toMany="true">
		<db-attribute-pair source="APPOINT_DATE" target="APPOINT_DATE"/>
		<db-attribute-pair source="APPOINT_NO" target="APPOINT_NO"/>
	</db-relationship>
	<db-relationship name="ActivitiesRel" source="RESULT" target="ACTIVITY" toMany="true">
		<db-attribute-pair source="APPOINT_DATE" target="APPOINT_DATE"/>
		<db-attribute-pair source="APPOINT_NO" target="APPOINT_NO"/>
	</db-relationship>
	<obj-relationship name="results" source="Activity" target="ActivityResult" collection-type="java.util.Map" map-key="field" deleteRule="Deny" db-relationship-path="ActivityResultsRel"/>
</data-map>

=== hiroyasub/cayenne-cregit/docs/doc/src/main/image-src/single-table-inheritance/UntitledDomainMap.map.xml
<?xml version="1.0" encoding="utf-8"?>
<data-map xmlns="http://cayenne.apache.org/schema/3.0/modelMap"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://cayenne.apache.org/schema/3.0/modelMap http://cayenne.apache.org/schema/3.0/modelMap.xsd"
  project-version="3.0.0.1">
	<property name="defaultPackage" value="org.example"/>
	<db-entity name="BOOK">
		<db-attribute name="AUTHOR" type="VARCHAR" length="500"/>
		<db-attribute name="DOWNLOAD_URL" type="VARCHAR" length="500"/>
		<db-attribute name="ID" type="BIGINT" isPrimaryKey="true" isMandatory="true"/>
		<db-attribute name="IN_STOCK" type="BOOLEAN"/>
		<db-attribute name="ISBN" type="CHAR" length="9"/>
		<db-attribute name="PRICE" type="DECIMAL"/>
		<db-attribute name="SHIPPING_WEIGHT" type="DECIMAL"/>
		<db-attribute name="SIZE_MB" type="DECIMAL"/>
		<db-attribute name="TITLE" type="VARCHAR" length="500"/>
		<db-attribute name="TYPE" type="CHAR" isMandatory="true" length="1"/>
	</db-entity>
	<obj-entity name="Book" className="org.example.Book" dbEntityName="BOOK">
		<obj-attribute name="author" type="java.lang.String" db-attribute-path="AUTHOR"/>
		<obj-attribute name="isbn" type="java.lang.String" db-attribute-path="ISBN"/>
		<obj-attribute name="price" type="java.math.BigDecimal" db-attribute-path="PRICE"/>
		<obj-attribute name="title" type="java.lang.String" db-attribute-path="TITLE"/>
		<obj-attribute name="type" type="java.lang.String" db-attribute-path="TYPE"/>
	</obj-entity>
	<obj-entity name="PaperBook" superEntityName="Book" className="org.example.PaperBook">
		<qualifier><![CDATA[type = "P"]]></qualifier>
	</obj-entity>
</data-map>

=== hiroyasub/cayenne-cregit/cayenne-crypto/src/test/resources/datamap.map.xml
<?xml version="1.0" encoding="utf-8"?>
<data-map xmlns="http://cayenne.apache.org/schema/7/modelMap"
	 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	 xsi:schemaLocation="http://cayenne.apache.org/schema/7/modelMap http://cayenne.apache.org/schema/7/modelMap.xsd"
	 project-version="7">
	<property name="defaultPackage" value="org.apache.cayenne.crypto.db"/>
	<db-entity name="TABLE1">
		<db-attribute name="CRYPTO_STRING" type="CLOB"/>
		<db-attribute name="ID" type="INTEGER" isPrimaryKey="true" isMandatory="true"/>
		<db-attribute name="PLAIN_STRING" type="VARCHAR" length="200"/>
	</db-entity>
	<obj-entity name="Table1" className="org.apache.cayenne.crypto.db.Table1" dbEntityName="TABLE1">
		<obj-attribute name="cryptoString" type="java.lang.String" db-attribute-path="CRYPTO_STRING"/>
		<obj-attribute name="plainString" type="java.lang.String" db-attribute-path="PLAIN_STRING"/>
	</obj-entity>
</data-map>

=== hiroyasub/cayenne-cregit/cayenne-server/src/test/resources/meaningful-pk.map.xml
<?xml version="1.0" encoding="utf-8"?>
<data-map xmlns="http://cayenne.apache.org/schema/7/modelMap"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://cayenne.apache.org/schema/7/modelMap http://cayenne.apache.org/schema/7/modelMap.xsd"
          project-version="7">
    <property name="defaultPackage" value="org.apache.cayenne.testdo.meaningful_pk"/>
    <property name="clientSupported" value="true"/>
    <property name="defaultClientPackage" value="org.apache.cayenne.testdo.meaningful_pk"/>
    <db-entity name="MEANINGFUL_PK">
        <db-attribute name="PK" type="VARCHAR" isPrimaryKey="true" isMandatory="true" length="100"/>
    </db-entity>
    <obj-entity name="MeaningfulPk" className="org.apache.cayenne.testdo.meaningful_pk.MeaningfulPk" clientClassName="org.apache.cayenne.testdo.meaningful_pk.ClientMeaningfulPk" dbEntityName="MEANINGFUL_PK">
        <obj-attribute name="pk" type="java.lang.String" db-attribute-path="PK"/>
    </obj-entity>
</data-map>

=== hiroyasub/cayenne-cregit/framework/cayenne-lifecycle/src/test/resources/lifecycle-map.map.xml
<?xml version="1.0" encoding="utf-8"?>
<data-map xmlns="http://cayenne.apache.org/schema/3.0/modelMap"
	 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	 xsi:schemaLocation="http://cayenne.apache.org/schema/3.0/modelMap http://cayenne.apache.org/schema/3.0/modelMap.xsd"
	 project-version="6">
	<property name="defaultPackage" value="org.apache.cayenne.lifecycle.db"/>
	<db-entity name="E1">
		<db-attribute name="ID" type="BIGINT" isPrimaryKey="true" isMandatory="true"/>
	</db-entity>
	<db-entity name="E2">
		<db-attribute name="ID" type="BIGINT" isPrimaryKey="true" isMandatory="true"/>
	</db-entity>
	<db-entity name="SORT_DEP">
		<db-attribute name="ID" type="BIGINT" isPrimaryKey="true" isMandatory="true"/>
		<db-attribute name="ROOT_ID" type="BIGINT" isMandatory="true"/>
	</db-entity>
	<db-entity name="SORT_ROOT">
		<db-attribute name="ID" type="INTEGER" isPrimaryKey="true" isMandatory="true"/>
	</db-entity>
	<db-entity name="UUID_ROOT1">
		<db-attribute name="ID" type="INTEGER" isPrimaryKey="true" isMandatory="true"/>
		<db-attribute name="UUID" type="VARCHAR" length="200"/>
	</db-entity>
	<obj-entity name="E1" className="org.apache.cayenne.lifecycle.db.E1" dbEntityName="E1">
	</obj-entity>
	<obj-entity name="E2" className="org.apache.cayenne.lifecycle.db.E2" dbEntityName="E2">
	</obj-entity>
	<obj-entity name="SortDep" className="org.apache.cayenne.lifecycle.db.SortDep" dbEntityName="SORT_DEP">
	</obj-entity>
	<obj-entity name="SortRoot" className="org.apache.cayenne.lifecycle.db.SortRoot" dbEntityName="SORT_ROOT">
	</obj-entity>
	<obj-entity name="UuidRoot1" className="org.apache.cayenne.lifecycle.db.UuidRoot1" dbEntityName="UUID_ROOT1">
		<obj-attribute name="uuid" type="java.lang.String" db-attribute-path="UUID"/>
	</obj-entity>
	<db-relationship name="root" source="SORT_DEP" target="SORT_ROOT" toMany="false">
		<db-attribute-pair source="ROOT_ID" target="ID"/>
	</db-relationship>
	<db-relationship name="deps" source="SORT_ROOT" target="SORT_DEP" toMany="true">
		<db-attribute-pair source="ID" target="ROOT_ID"/>
	</db-relationship>
	<obj-relationship name="root" source="SortDep" target="SortRoot" deleteRule="Nullify" db-relationship-path="root"/>
	<obj-relationship name="deps" source="SortRoot" target="SortDep" deleteRule="Deny" db-relationship-path="deps"/>
</data-map>

=== hiroyasub/cayenne-cregit/framework/cayenne-jdk1.5-unpublished/src/test/resources/const.map.xml
<?xml version="1.0" encoding="utf-8"?>
<data-map xmlns="http://cayenne.apache.org/schema/3.0/modelMap"
	 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	 xsi:schemaLocation="http://cayenne.apache.org/schema/3.0/modelMap http://cayenne.apache.org/schema/3.0/modelMap.xsd"
	 project-version="6">
	<property name="defaultPackage" value="org.apache.cayenne.testdo.consttest"/>
	<db-entity name="CONST1_ENTITY">
		<db-attribute name="ID" type="BIGINT" isPrimaryKey="true" isMandatory="true"/>
		<db-attribute name="NAME" type="CHAR" isMandatory="true" length="200"/>
		<db-attribute name="STATUS" type="INTEGER" isMandatory="false"/>
		<db-attribute name="TYPE" type="INTEGER" isMandatory="true"/>
	</db-entity>
	<obj-entity name="Const1Entity" className="org.apache.cayenne.testdo.consttest.Const1Entity" dbEntityName="CONST1_ENTITY">
		<obj-attribute name="name" type="java.lang.String" db-attribute-path="NAME"/>
		<obj-attribute name="status" type="java.lang.Integer" db-attribute-path="STATUS"/>
		<obj-attribute name="type" type="org.apache.cayenne.testdo.consttest.Const1Type" db-attribute-path="TYPE"/>
	</obj-entity>
</data-map>

=== hiroyasub/cayenne-cregit/cayenne-server/src/test/resources/java8.map.xml
<?xml version="1.0" encoding="utf-8"?>
<data-map xmlns="http://cayenne.apache.org/schema/10/modelMap"
	 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	 xsi:schemaLocation="http://cayenne.apache.org/schema/10/modelMap https://cayenne.apache.org/schema/10/modelMap.xsd"
	 project-version="10">
	<property name="defaultPackage" value="org.apache.cayenne.testdo.java8"/>
	<db-entity name="DURATION_TEST">
		<db-attribute name="DurationBigInt" type="BIGINT"/>
		<db-attribute name="DurationDecimal" type="DECIMAL"/>
		<db-attribute name="DurationInt" type="INTEGER" length="100"/>
		<db-attribute name="DurationLongNVarchar" type="LONGNVARCHAR" length="100"/>
		<db-attribute name="DurationLongVarchar" type="LONGVARCHAR" length="100"/>
		<db-attribute name="DurationNVarchar" type="NVARCHAR" length="100"/>
		<db-attribute name="DurationNumeric" type="NUMERIC"/>
		<db-attribute name="DurationVarchar" type="VARCHAR" length="100"/>
		<db-attribute name="ID" type="INTEGER" isPrimaryKey="true" isMandatory="true"/>
	</db-entity>
	<db-entity name="LOCAL_DATETIME_TEST">
		<db-attribute name="ID" type="INTEGER" isPrimaryKey="true" isMandatory="true"/>
		<db-attribute name="TimestampField" type="TIMESTAMP"/>
	</db-entity>
	<db-entity name="LOCAL_DATE_TEST">
		<db-attribute name="DateField" type="DATE"/>
		<db-attribute name="ID" type="INTEGER" isPrimaryKey="true" isMandatory="true"/>
	</db-entity>
	<db-entity name="LOCAL_TIME_TEST">
		<db-attribute name="ID" type="INTEGER" isPrimaryKey="true" isMandatory="true"/>
		<db-attribute name="TimeField" type="TIME"/>
	</db-entity>
	<db-entity name="PERIOD_TEST">
		<db-attribute name="ID" type="INTEGER" isPrimaryKey="true" isMandatory="true"/>
		<db-attribute name="PeriodField" type="VARCHAR" length="100"/>
	</db-entity>
	<obj-entity name="DurationTest" className="org.apache.cayenne.testdo.java8.DurationTestEntity" dbEntityName="DURATION_TEST">
		<obj-attribute name="durationVarchar" type="java.time.Duration" db-attribute-path="DurationVarchar"/>
		<obj-attribute name="durationBigInt" type="java.time.Duration" db-attribute-path="DurationBigInt"/>
		<obj-attribute name="durationNumeric" type="java.time.Duration" db-attribute-path="DurationNumeric"/>
		<obj-attribute name="durationDecimal" type="java.time.Duration" db-attribute-path="DurationDecimal"/>
		<obj-attribute name="durationLongVarchar" type="java.time.Duration" db-attribute-path="DurationLongVarchar"/>
		<obj-attribute name="durationNVarchar" type="java.time.Duration" db-attribute-path="DurationNVarchar"/>
		<obj-attribute name="durationLongNVarchar" type="java.time.Duration" db-attribute-path="DurationLongNVarchar"/>
		<obj-attribute name="durationInt" type="java.time.Duration" db-attribute-path="DurationInt"/>
	</obj-entity>
	<obj-entity name="LocalDateTest" className="org.apache.cayenne.testdo.java8.LocalDateTestEntity" dbEntityName="LOCAL_DATE_TEST">
		<obj-attribute name="date" type="java.time.LocalDate" db-attribute-path="DateField"/>
	</obj-entity>
	<obj-entity name="LocalDateTimeTest" className="org.apache.cayenne.testdo.java8.LocalDateTimeTestEntity" dbEntityName="LOCAL_DATETIME_TEST">
		<obj-attribute name="timestamp" type="java.time.LocalDateTime" db-attribute-path="TimestampField"/>
	</obj-entity>
	<obj-entity name="LocalTimeTest" className="org.apache.cayenne.testdo.java8.LocalTimeTestEntity" dbEntityName="LOCAL_TIME_TEST">
		<obj-attribute name="time" type="java.time.LocalTime" db-attribute-path="TimeField"/>
	</obj-entity>
	<obj-entity name="PeriodTest" className="org.apache.cayenne.testdo.java8.PeriodTestEntity" dbEntityName="PERIOD_TEST">
		<obj-attribute name="periodField" type="java.time.Period" db-attribute-path="PeriodField"/>
	</obj-entity>
</data-map>

=== hiroyasub/cayenne-cregit/framework/cayenne-jdk1.5-unpublished/src/test/resources/inheritance-vertical.map.xml
<?xml version="1.0" encoding="utf-8"?>
<data-map xmlns="http://cayenne.apache.org/schema/3.0/modelMap"
	 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	 xsi:schemaLocation="http://cayenne.apache.org/schema/3.0/modelMap http://cayenne.apache.org/schema/3.0/modelMap.xsd"
	 project-version="6">
	<property name="defaultPackage" value="org.apache.cayenne.testdo.inheritance.vertical"/>
	<db-entity name="IV_ROOT">
		<db-attribute name="ID" type="INTEGER" isPrimaryKey="true" isMandatory="true"/>
		<db-attribute name="NAME" type="VARCHAR" length="100"/>
	</db-entity>
	<db-entity name="IV_SUB1">
		<db-attribute name="ID" type="INTEGER" isPrimaryKey="true" isMandatory="true"/>
		<db-attribute name="SUB1_NAME" type="VARCHAR" length="100"/>
	</db-entity>
	<db-entity name="IV_SUB1_SUB1">
		<db-attribute name="ID" type="INTEGER" isPrimaryKey="true" isMandatory="true"/>
		<db-attribute name="SUB1_SUB1_NAME" type="VARCHAR" length="100"/>
	</db-entity>
	<db-entity name="IV_SUB2">
		<db-attribute name="ID" type="INTEGER" isPrimaryKey="true" isMandatory="true"/>
		<db-attribute name="NAME" type="VARCHAR" length="100"/>
		<db-attribute name="SUB2_NAME" type="VARCHAR" length="100"/>
	</db-entity>
	<obj-entity name="IvRoot" className="org.apache.cayenne.testdo.inheritance.vertical.IvRoot" dbEntityName="IV_ROOT">
		<obj-attribute name="name" type="java.lang.String" db-attribute-path="NAME"/>
	</obj-entity>
	<obj-entity name="IvSub1" superEntityName="IvRoot" className="org.apache.cayenne.testdo.inheritance.vertical.IvSub1" dbEntityName="IV_SUB1">
		<obj-attribute name="sub1Name" type="java.lang.String" db-attribute-path="SUB1_NAME"/>
	</obj-entity>
	<obj-entity name="IvSub1Sub1" superEntityName="IvSub1" className="org.apache.cayenne.testdo.inheritance.vertical.IvSub1Sub1" dbEntityName="IV_SUB1_SUB1">
		<obj-attribute name="sub1Sub1Name" type="java.lang.String" db-attribute-path="SUB1_SUB1_NAME"/>
	</obj-entity>
	<obj-entity name="IvSub2" superEntityName="IvRoot" className="org.apache.cayenne.testdo.inheritance.vertical.IvSub2" dbEntityName="IV_SUB2">
		<obj-attribute name="sub2Name" type="java.lang.String" db-attribute-path="SUB2_NAME"/>
	</obj-entity>
	<db-relationship name="sub1" source="IV_ROOT" target="IV_SUB1" toDependentPK="true" toMany="false">
		<db-attribute-pair source="ID" target="ID"/>
	</db-relationship>
	<db-relationship name="sub2" source="IV_ROOT" target="IV_SUB2" toDependentPK="true" toMany="false">
		<db-attribute-pair source="ID" target="ID"/>
	</db-relationship>
	<db-relationship name="master" source="IV_SUB1" target="IV_ROOT" toMany="false">
		<db-attribute-pair source="ID" target="ID"/>
	</db-relationship>
	<db-relationship name="sub1Sub1" source="IV_SUB1" target="IV_SUB1_SUB1" toDependentPK="true" toMany="false">
		<db-attribute-pair source="ID" target="ID"/>
	</db-relationship>
	<db-relationship name="master" source="IV_SUB1_SUB1" target="IV_SUB1" toMany="false">
		<db-attribute-pair source="ID" target="ID"/>
	</db-relationship>
	<db-relationship name="master" source="IV_SUB2" target="IV_ROOT" toMany="false">
		<db-attribute-pair source="ID" target="ID"/>
	</db-relationship>
</data-map>
